version: '3.8'

services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Porta para acesso externo opcional

  api:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app # Monta o código para desenvolvimento/observação
    depends_on:
      - db # Garante que o banco suba primeiro
    env_file:
      - .env # Carrega as variáveis de ambiente

volumes:
  postgres_data:
